# Site settings
title: opengl-tutorial
email: contact@opengl-tutorial.org
description: "This site is dedicated to tutorials for OpenGL 3.3 and later !"
baseurl: ""
highlighter: pygments
safe: true
lsi: false
source:      .
languages: [en, cn, jp, ru]
languages_names: [english, chinese, japanese, russian]
# Build settings
markdown: kramdown
permalink: pretty
