# Site settings
title: opengl-tutorials
email: contact@opengl-tutorial.org
description: "This site is dedicated to tutorials for OpenGL 3.3 and later !"
baseurl: "/opengl-tutorials"
highlighter: pygments
safe: true
lsi: false
source:      .

# Build settings
markdown: kramdown
permalink: pretty
